# Nebula Universal Development Server Configuration
# This is the default configuration file

[server]
domain = "app.nebula.com"
http_port = 3000
https_port = 3443
command = "npm run dev"
hot_reload = true
mode = "dev"
request_timeout = 30
keep_alive_timeout = 60
max_connections = 1000
enable_http2 = true
compression = true

[tls]
cert_dir = "~/.local/share/nebula/certs"
auto_generate = true
ca_name = "Nebula Development CA"
key_type = "ecdsa"
validity_days = 365
auto_renew = true
renew_days_before = 30

[dns]
enabled = true
port = 53
bind_address = "127.0.0.1"
cache_size = 1024
cache_ttl = 300
upstream = ["8.8.8.8:53", "1.1.1.1:53"]
forwarding = true
recursion = true

[dhcp]
enabled = false
range_start = "192.168.100.100"
range_end = "192.168.100.200"
lease_time = 86400
renewal_time = 43200
rebinding_time = 75600
subnet_mask = "255.255.255.0"
dns_servers = ["127.0.0.1"]
domain_name = "nebula.local"

[scheduler]
enabled = true
default_tld = "xyz"
dev_tld = "nebula.com"
storage_path = "~/.local/share/nebula/scheduler"
max_concurrent_deployments = 10
auto_cleanup = true
cleanup_after_days = 30
health_check_interval = 30
restart_policy = "always"

[logging]
level = "info"
max_size = 10485760  # 10MB
max_files = 5
format = "text"
enable_colors = true

[dev]
watch_patterns = ["src/**/*", "public/**/*", "static/**/*", "assets/**/*"]
ignore_patterns = [
    "node_modules/**/*",
    ".git/**/*",
    "target/**/*",
    "dist/**/*",
    "build/**/*",
    "*.log",
    ".DS_Store",
    "Thumbs.db"
]
restart_delay = 500
auto_open_browser = false

[dev.env]
NODE_ENV = "development"
