[server]
domain = "app.nebula.com"
http_port = 5000
https_port = 5443
command = "dotnet run"
hot_reload = true
mode = "dev"

[tls]
cert_dir = "~/.local/share/nebula/certs"
auto_generate = true
ca_name = "Nebula Development CA"

[dns]
enabled = true
port = 53
cache_size = 1024
upstream = ["8.8.8.8:53", "1.1.1.1:53"]

[dhcp]
enabled = false

[scheduler]
enabled = true
default_tld = "xyz"
dev_tld = "nebula.com"

[dev]
watch_patterns = ["**/*.cs", "**/*.csproj", "appsettings*.json"]
ignore_patterns = ["bin/**/*", "obj/**/*", ".git/**/*"]
restart_delay = 2000
auto_open_browser = false

[dev.env]
ASPNETCORE_ENVIRONMENT = "Development"
DOTNET_WATCH_RESTART_ON_RUDE_EDIT = "true"
