[server]
domain = "app.nebula.com"
http_port = 8080
https_port = 8443
command = "./mvnw spring-boot:run"
hot_reload = true
mode = "dev"

[tls]
cert_dir = "~/.local/share/nebula/certs"
auto_generate = true
ca_name = "Nebula Development CA"

[dns]
enabled = true
port = 53
cache_size = 1024
upstream = ["8.8.8.8:53", "1.1.1.1:53"]

[dhcp]
enabled = false

[scheduler]
enabled = true
default_tld = "xyz"
dev_tld = "nebula.com"

[dev]
watch_patterns = ["src/**/*.java", "src/main/resources/**/*", "pom.xml"]
ignore_patterns = ["target/**/*", ".git/**/*"]
restart_delay = 3000
auto_open_browser = false

[dev.env]
JAVA_OPTS = "-Dspring.profiles.active=dev"
MAVEN_OPTS = "-Xmx1024m"
