[server]
domain = "app.nebula.com"
http_port = 3000
https_port = 3443
command = "rails server"
hot_reload = true
mode = "dev"

[tls]
cert_dir = "~/.local/share/nebula/certs"
auto_generate = true
ca_name = "Nebula Development CA"

[dns]
enabled = true
port = 53
cache_size = 1024
upstream = ["8.8.8.8:53", "1.1.1.1:53"]

[dhcp]
enabled = false

[scheduler]
enabled = true
default_tld = "xyz"
dev_tld = "nebula.com"

[dev]
watch_patterns = ["app/**/*", "config/**/*", "Gemfile"]
ignore_patterns = ["log/**/*", "tmp/**/*", ".git/**/*"]
restart_delay = 1000
auto_open_browser = false

[dev.env]
RAILS_ENV = "development"
BUNDLE_PATH = "vendor/bundle"
